services:
  nginx:
    container_name: library-nginx
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./api:/var/www/html
    depends_on:
      - php
    networks:
      - library-api-network

  php:
    container_name: library-php
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
    depends_on:
      - mysql
    networks:
      - library-api-network

  mysql:
    container_name: library-mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: library
      MYSQL_USER: library
      MYSQL_PASSWORD: library
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - library-api-network

networks:
  library-api-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
